 
 
DROP TABLE IF EXISTS airlines ;
CREATE TABLE airlines (id CHAR(2) PRIMARY KEY,name VARCHAR(30)  ); 
LOAD DATA LOCAL INFILE 'C:/Users/xu7719/Downloads/ee-egr/EE-656/Assignment-1/airlines.csv' INTO TABLE airlines  FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 ROWS; 


DROP TABLE IF EXISTS airports ;
CREATE TABLE airports   (id CHAR(3) PRIMARY KEY, 
						   name VARCHAR(255) NULL ,   
							city VARCHAR(255) NULL ,   
						   state VARCHAR(255) NULL ,   
							country VARCHAR(255) NULL ,  
							 latitude  FLOAT NULL ,  
							longitude FLOAT NULL   );
LOAD DATA LOCAL INFILE 'C:/Users/xu7719/Downloads/ee-egr/EE-656/Assignment-1/airports.csv' INTO TABLE airports  FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 ROWS; 
 
 
DROP TABLE IF EXISTS flights ;
CREATE TABLE flights ( YEAR INT, MONTH INT,  DAY INT,  DAY_OF_WEEK INT,  AIRLINE CHAR(10),  
  FLIGHT_NUMBER INT, TAIL_NUMBER VARCHAR(10),  ORIGIN_AIRPORT VARCHAR(10), DESTINATION_AIRPORT VARCHAR(10),  
  SCHEDULED_DEPARTURE INT, DEPARTURE_TIME INT, DEPARTURE_DELAY INT, TAXI_OUT INT, WHEELS_OFF INT, SCHEDULED_TIME INT,  
  ELAPSED_TIME INT,AIR_TIME INT, DISTANCE INT, WHEELS_ON INT, TAXI_IN INT, SCHEDULED_ARRIVAL INT, ARRIVAL_TIME INT,  
  ARRIVAL_DELAY INT, DIVERTED INT,CANCELLED INT, CANCELLATION_REASON CHAR(10), AIR_SYSTEM_DELAY CHAR(10),   
  SECURITY_DELAY CHAR(10),  AIRLINE_DELAY CHAR(10), LATE_AIRCRAFT_DELAY CHAR(10), WEATHER_DELAY CHAR(10) );
 
LOAD DATA LOCAL INFILE 'C:/Users/xu7719/Downloads/ee-egr/EE-656/Assignment-1/flights_clean.csv' INTO TABLE flights  FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' IGNORE 1 ROWS; 

 
  